version: "3.7"

# Usage: docker-compose up <service name>
# All variables are specified in the .env file

services:

# Base container with command-line R interface
  base:
    image: "quay.io/rajivnarayan/carte-r:latest"
    env_file: .env
    environment:
        PASSWORD: ${CARTE_PASSWORD?:err}
        SUDO: "true"
        # user id of carte user
        USERID: ${HOST_UID}
    entrypoint: "/init"
    volumes:
      # bind mount specified host folder
    - type: bind
      source: ${BIND_VOLUME:?err}
      target: /work
      #stdin_open: true
      #tty: true

# A full-fledged container with R, Rstudio, and Opencpu
# The host folder specified by $BIND_VOLUME is 
# mounted in the container as /work
  full :
    image: "quay.io/rajivnarayan/carte-r:latest"

    # read variables from the .env file
    env_file: .env
       
    environment:
        # rstudio login password
        PASSWORD: ${CARTE_PASSWORD?:err}
        # add carte user to sudo group
        SUDO: "true"
        # user id of carte user
        USERID: ${HOST_UID}
        # enable rstudio if true
        ADD_RSTUDIO: "true"
        # enable shiny if true
        ADD_SHINY: "false"
        # enable opencpu if true
        ADD_OPENCPU: "true"
    
    volumes:
      # bind mount specified host folder
      - type: bind
        source: ${BIND_VOLUME:?err}
        target: /work
   
    # Port mapping from the container to the host
    ports:
    # Rstudio: http://localhost:$RSTUDIO_PORT
      - "${RSTUDIO_PORT}:8787"
    # Shiny
    #  - "${SHINY_PORT}:3838"
    # OpenCPU HTTP 
    # Opencpu endpoint: http://localhost:$OPENCPU_HTTP_PORT/ocpu
    # Rstudio procy: http://localhost:$OPENCPU_HTTP_PORT/rstudio
      - "${OPENCPU_HTTP_PORT}:80"
    # OpenCPU HTTPS for secure http (needs ssl certs to be configured)
    #  - "${OPENCPU_HTTPS_PORT}:443"
    
    entrypoint: "/init"

