#!/usr/bin/with-contenv bash

ADD_RSTUDIO=${ADD_RSTUDIO:=none}

RSTUDIO_VERSION=${RSTUDIO_VERSION:-1.1.447}
export PATH=/usr/lib/rstudio-server/bin:$PATH

if [[ $ADD_RSTUDIO == 'true' ]]; then
	echo "Installing RStudio server to the container..."
	## Attempts to get detect latest version, otherwise falls back to version given in $VER
	## Symlink pandoc, pandoc-citeproc so they are available system-wide
	apt-get update
	apt-get install -y --no-install-recommends gdebi-core git
	RSTUDIO_LATEST=$(wget --no-check-certificate -qO- https://s3.amazonaws.com/rstudio-server/current.ver) 
	[ -z "$RSTUDIO_VERSION" ] && RSTUDIO_VERSION=$RSTUDIO_LATEST || true 
	wget -q http://download2.rstudio.org/rstudio-server-${RSTUDIO_VERSION}-amd64.deb 
	gdebi -n rstudio-server-${RSTUDIO_VERSION}-amd64.deb
	rm rstudio-server-*-amd64.deb
	## Symlink pandoc & standard pandoc templates for use system-wide
	ln -s /usr/lib/rstudio-server/bin/pandoc/pandoc /usr/local/bin
	ln -s /usr/lib/rstudio-server/bin/pandoc/pandoc-citeproc /usr/local/bin
	git clone https://github.com/jgm/pandoc-templates
	mkdir -p /opt/pandoc/templates
	cp -r pandoc-templates*/* /opt/pandoc/templates && rm -rf pandoc-templates*
	mkdir /root/.pandoc && ln -s /opt/pandoc/templates /root/.pandoc/templates
	apt-get clean
	rm -rf /var/lib/apt/lists/ 
	## RStudio wants an /etc/R, will populate from $R_HOME/etc
	mkdir -p /etc/R
	## Write config files in $R_HOME/etc
	echo -e '\n
	\n# Configure httr to perform out-of-band authentication if HTTR_LOCALHOST
	\n# is not set since a redirect to localhost may not work depending upon
	\n# where this Docker container is running.
	\nif(is.na(Sys.getenv("HTTR_LOCALHOST", unset=NA))) {
	\n  options(httr_oob_default = TRUE)
	\n}' >> /usr/lib/R/etc/Rprofile.site

	echo "PATH=${PATH}" >> /usr/lib/R/etc/Renviron

	## use more robust file locking to avoid errors when using shared volumes:
	echo 'lock-type=advisory' >> /etc/rstudio/file-locks
	## configure git not to request password each time
	git config --system credential.helper 'cache --timeout=3600'
	git config --system push.default simple
  else
	echo -e "Not installing RStudio.\n
		  To install at run time specify -e ADD_RSTUDIO=true to the 
		  Docker run command.\n
		  To install within a container run:\n
		  export ADD_RSTUDIO=true && bash /etc/cont-init.d/add_rstudio
		  " 
  fi
